name: Barter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  flutter_bloc: ^8.1.3
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_svg: ^2.1.0
  flutter_launcher_icons: ^0.14.4


  cupertino_icons: ^1.0.8
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/duck.png
    - assets/images/birJolLogo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/duck.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/duck.png"
  windows:
    generate: true
    image_path: "assets/images/duck.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/duck.png"
