name: BirJol
description: "A Kyrgyz ride-sharing app - the local version of BlaBlaCar."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  flutter_bloc: ^8.1.3
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_svg: ^2.1.0
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  http: ^1.1.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  intl: ^0.19.0
  url_launcher: ^6.2.2
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/duck.png
    - assets/images/birJolLogo.png
    # - assets/images/placeholder_avatar.png
    # - assets/images/car_placeholder.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/birJolLogo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/birJolLogo.png"
  windows:
    generate: true
    image_path: "assets/images/birJolLogo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/birJolLogo.png"
